### ISSUE TITLE
Projects do not show up on the projects page

### ISSUE THREAD

**Issue by KoenBal** [Qlik-Branch/branch-resource-library#149]
Hello,

I'm trying to search for a project on the qlik Branch website but nothing shows up. Can I access the projects in a different way?
I'm looking for the comments of the rvspt/D3DynamicTreeLayout-QV project in particular.

,Thanks in advance

![qlik branch project search unresponsive](https://cloud.githubusercontent.com/assets/5289035/11950884/e5edb8b6-a88c-11e5-8068-0cf53b073d53.PNG)

**Comment by brianwmunz** [comment]
Sorry about that.  We had to turn something off to test it and it didn't get turned back on properly.  Everything should now be working.
Thanks

**Comment by KoenBal** [comment]
Great :),  thanks for the fast reply,  hope to be contributing soon

**Comment by KoenBal** [comment]
Same issue appeared again.

,KR Koen
