### ISSUE TITLE
Button "Login with GitHub" not working

### ISSUE THREAD

**Issue by KoenBal** [Qlik-Branch/branch-resource-library#171]
Hello,

The button "Login with GitHub" doesn't seem to work. Should it open a popup? Does my browser block anything?

![github login button](https://cloud.githubusercontent.com/assets/5289035/13490471/1d9dd204-e12d-11e5-90ba-1f80c7daacb0.PNG)

,Kr Koen

**Comment by websy85** [comment]
Hi,
Can you provide more information on what's happening when you try to login? Take a look at this article which describes how the process works - [http://branch.qlik.com/#/blog/56b47d2223d7df64273983d1](url)
Nick

**Comment by KoenBal** [comment]
Problem is fixed now. It didn't do anything. The button just blinked.
