### ISSUE TITLE
Need to change the points display

### ISSUE THREAD

**Issue by brianwmunz** [Qlik-Branch/branch-resource-library#241]
At minimum we need to be more obvious about what the number means on the project listing page. People think it's number of downloads. I'd probably prefer moving from a star system to a like & flag system. Or just figure a better way to show stars

**Comment by websy85** [comment]
What about putting the word 'points' underneath and create a page/popup that shows how stars relate to points? Even better change stars to points so it matches up and put 'total points' underneath. I still argue that points is more useful. With stars, a project with 1 rating of 5 stars could appear above a project with 5 ratings of 5 stars. With points that would be 5 vs 25, a clear difference and way more useful when deciding on a project to use.

**Comment by mindspank** [comment]
I'm also in favor of points and digging the ^ suggestion.
In addition to this I think we should calculate some decay rate on the points so we can have "Lifetime points" and "Popular Projects". As it stands now new projects have a hard time breaking into the top 5

**Comment by websy85** [comment]
yeah that'd be cool. trending projects!

**Comment by yianni-ververis** [comment]
I do not see anywhere number of downloads. Usually that is an indicator about the popularity of the project. 
So top 5 would be a combination of points/stars or thumbsup like stackoverflow, views, downloads and life of the projects

**Comment by yianni-ververis** [comment]
Well maybe not in the sort by popular filer. Maybe we add another one that is sort by downloads.

**Comment by countnazgul** [comment]
Points with decay rate seems very reasonable. Also popup explaining what the number represents is not a bad idea. 

**And wild idea about extensions/mashups:** what about having "extension analytics" code that is embedded into the extension which send usage statistics (to where is another story). This will give the actual usage. The usage then can be combined with the downloads and ratings numbers to position the project (or just give an idea to the developers how much is used and how many users/installations are using it) ... **just a completely random idea** :)

**Comment by rjriel** [comment]
I like the ideas that @yianni-ververis and @countnazgul are suggesting but unfortunately since we have users host their projects on GitHub we have now real way of tracking downloads and we can't inject code into the extensions.

**Comment by brianwmunz** [comment]
cleaning up my open issues and Branch isn't really a thing anymore
