### ISSUE TITLE
Blog thumbnails are stretched

### ISSUE THREAD

**Issue by mindspank** [Qlik-Branch/branch-resource-library#259]
The blog thumbnails on the Home route have strange aspect ratio and looks stretched

**Comment by mindspank** [comment]
@brianwmunz Didn't this commit https://github.com/Qlik-Branch/branch-resource-library/commit/395788936b7b9fd95f461df4e3f5f5582f9dc880 close this?

**Comment by rjriel** [comment]
no, did not fully commit. While @brianwmunz updated the .less files, the built files were not committed
