### ISSUE TITLE
Markdown parser of readme.md slightly off

### ISSUE THREAD

**Issue by mindspank** [Qlik-Branch/branch-resource-library#262]
Compare https://github.com/mountaindude/sense-template-app-duplicate/blob/master/README.md and http://branch.qlik.com/#!/project/58600013de3d527f18ef38e9

After the images halfway through the readme.md we loose formatting on the Branch side for heading directly after images. Specifically https://github.com/mountaindude/sense-template-app-duplicate/blob/master/README.md#requirements-and-installation which is not formatted correctly on the Branch side.

**Comment by rjriel** [comment]
is that the only formatting loss you noticed? That seems to be a css thing, which I'm looking at now, so I'm not sure there would be other issues there

**Comment by rjriel** [comment]
h1 under project details has been updated, unaware of any other issues RE markdown
